### ISSUE TITLE
AE2 Engineering Processor quest requires a Calculation Processor

### ISSUE THREAD

**Issue by imartsify** [ThePansmith/Enigmatica2ExpertUnofficial#10]
**Modpack version**
1.0.5

**Issue**
When working though the new AE2 quests, I discovered that the engineering processor quest is completed with a calculation processor.

The calculation processor quest is correct however.

**Logs**

**Comment by ThePansmith** [comment]
Thanks for submitting! Fixed in 9bc2250.
