### ISSUE TITLE
Thaumcraft Hedge alchemy broken.

### ISSUE THREAD

**Issue by PopLamina** [ThePansmith/Enigmatica2ExpertUnofficial#11]
**Modpack version**
1.2.0.0

**Issue**
Hedge alchemy string to cobweb recipe is broken due to Thaumatic Speedup.

**Comment by PopLamina** [comment]
![image](https://user-images.githubusercontent.com/65089328/229357502-bbddbb4e-bdf5-496c-a3a4-ba2bb4f15cad.png)

**Comment by PopLamina** [comment]
The aspect draco also appears to be broken due to thaumatic speedup

**Comment by ThePansmith** [comment]
"Fixed" in 1.2.1.0 by removing TC speedup. I'll have to see about getting rong to update the mod.

**Comment by Anthonity** [comment]
> ![image](https://user-images.githubusercontent.com/65089328/229357502-bbddbb4e-bdf5-496c-a3a4-ba2bb4f15cad.png)

wasnt it always broken or is my memory warped /pi
