### ISSUE TITLE
Will there be a lite version?

### ISSUE THREAD

**Issue by TheAirBlow** [ThePansmith/Enigmatica2ExpertUnofficial#12]
Just wondering. This modpack is certanly not for 6 GB alloc, as it has ~420 mods.

Will there ever exist a lite version with at least half of mods removed? It's certanly possible to take this down to 200.

**Comment by Spicierspace153** [comment]
no

**Comment by Spicierspace153** [comment]
no

**Comment by Spicierspace153** [comment]
maybe once I have time
