### ISSUE TITLE
Add Thaumic Augmentation

### ISSUE THREAD

**Issue by Anthonity** [ThePansmith/Enigmatica2ExpertUnofficial#13]
**Modpack version**
1.3.0.0

**Issue**
Thaumcraft is a wonderful mod, however, the 1.12.2 version is unfinished and unpolished. Thaumic Augmentation is an wonderful addon which adds lots of new content mostly inspired by Thaumcraft 4/5 and the like. Thaumcraft is my favorite magic mod and I would be so awesome.

**Comment by MorphoKnight** [comment]
A few more thaumic addons that (imo) should get included:
Thaumic wonders: Adds new and actually original thaumic content: https://www.curseforge.com/minecraft/mc-mods/thaumic-wonders
Thaumic Fixes: fixes one (1) GUI bug https://www.curseforge.com/minecraft/mc-mods/thaumic-fixes
Thaumic Periphery: Small mod adding some integration with botania, renders some baubles, and adds some new gear https://www.curseforge.com/minecraft/mc-mods/thaumic-periphery
Rustic Thaumaturgy: Small mod linking rustic and thaumcraft https://www.curseforge.com/minecraft/mc-mods/rustic-thaumaturgy

**Comment by Anthonity** [comment]
> A few more thaumic addons that (imo) should get included: Thaumic WAILA: more WAILA Info displayed https://www.curseforge.com/minecraft/mc-mods/thaumicwaila Thaumic wonders: Adds new and actually original thaumic content: https://www.curseforge.com/minecraft/mc-mods/thaumic-wonders Thaumic Fixes: fixes one (1) GUI bug https://www.curseforge.com/minecraft/mc-mods/thaumic-fixes Thaumic Periphery: Small mod adding some integration with botania, renders some baubles, and adds some new gear https://www.curseforge.com/minecraft/mc-mods/thaumic-periphery Rustic Thaumaturgy: Small mod linking rustic and thaumcraft https://www.curseforge.com/minecraft/mc-mods/rustic-thaumaturgy

wowzers

**Comment by ThePansmith** [comment]
added in 1.3.8
