### ISSUE TITLE
Loot crates can still give you removed Extreme Reactors gems

### ISSUE THREAD

**Issue by Anthonity** [ThePansmith/Enigmatica2ExpertUnofficial#14]
**Modpack version**
1.3.0.0

**Issue**
ER has been removed, but the loot crate lootables still contain the deprecated gems. So you can get a bugged item
![2023-04-16_08 34 37](https://user-images.githubusercontent.com/93783103/232277561-b0a31a9a-f87d-421a-b0fa-c4d5f5e69df9.png)

**Comment by ThePansmith** [comment]
Fixed in 1.3.2.0
