### ISSUE TITLE
Unable to charge Multi Builder Tool and complete quest

### ISSUE THREAD

**Issue by TheRymGaming** [ThePansmith/Enigmatica2ExpertUnofficial#15]
**Modpack version**
1.3.5.0

**Issue**
Attempted to charge Multi Builder Tool in Mekanism Energy Cube, charging pad, Immersive Engineering Charging station, Ender IO charging stations, and with other portable chargers. The tool only charges to 10 rf, this also prevents completion of quest as it request a fully charged tool. Tested on 3 different worlds, one being a fresh world.

**Comment by ThePansmith** [comment]
"fixed" in 1.3.7 by changing quest requirements
