### ISSUE TITLE
Quest Book Task Not Auto Completing

### ISSUE THREAD

**Issue by TheRymGaming** [ThePansmith/Enigmatica2ExpertUnofficial#16]
**Modpack version**
1.3.5

**Issue**
You must manually detect/submit quest now. Previously the book would auto-detect, and if you got an item ahead of time on a locked quest, once it unlocked you auto completed it too. Now you must re-pickup items that you already obtained and hit detect/submit for the quest to recognize the items. 

Side note: There is an edit button to change quest parameters in the quest book/pages now, not sure if that was intentionally left in

**Comment by Anthonity** [comment]
disable edit mode

**Comment by ThePansmith** [comment]
fixed in 1.3.6
