### ISSUE TITLE
Unable to craft Sulfuric Acid Buckets, and therefore Draconium Crystals and the Chemical Dissolution Chamber.

### ISSUE THREAD

**Issue by Knifepony** [ThePansmith/Enigmatica2ExpertUnofficial#17]
1.3.5
Input modpack version here

Even with a fluid transposer, sulfuric acid buckets are impossible to craft. One also cannot get sulfuric acid buckets via using buckets on a chemical condenserator. 
Input short description of the issue here

**Logs**
Luckily, this doesn't crash the server. Or the game. Just needs a cheat for now, which I did.

**Comment by ThePansmith** [comment]
fixed in 1.3.6
