### ISSUE TITLE
AppliedEnergistics2 missing recipes

### ISSUE THREAD

**Issue by Cianelli21** [ThePansmith/Enigmatica2ExpertUnofficial#22]
**Modpack version**
1.3.6

**Issue**
missing recipes from AppliedEnergistics2 (ME Controller, Dense Cables)

**Comment by Cianelli21** [comment]
also missing in the E2EuS pack 1.3.6

**Comment by ThePansmith** [comment]
https://github.com/ThePansmith/Enigmatica2ExpertUnofficial/blob/master/overrides/scripts/Channels.zs

**Comment by Cianelli21** [comment]
sorry 

thank you for letting me know
