### ISSUE TITLE
Wrong sieve recipe

### ISSUE THREAD

**Issue by Dalailamer0684** [ThePansmith/Enigmatica2ExpertUnofficial#23]
**Modpack version**
1.3.7.3

**Issue**
Sieve recipe: 
2 Nickel Plates
1 Enriched Alloy
1 Mana Infused Gear 
2 Planks
2 Sticks

**Logs**
No crash
![2023-05-18 23_23_23-Enigmatica 2_ Expert Unofficial Skyblock](https://github.com/ThePansmith/Enigmatica2ExpertUnofficial/assets/101457811/8d06884d-4d47-4874-8207-4833d18257d7)

**Comment by Anthonity** [comment]
That is a balance change by the original dev

**Comment by Dalailamer0684** [comment]
> That is a balance change by the original dev

THX
I understand putting create in a modpack but why gating stuff behind the worst MC Mod???
