### ISSUE TITLE
Amber dupe

### ISSUE THREAD

**Issue by Anthonity** [ThePansmith/Enigmatica2ExpertUnofficial#24]
**Modpack version**
1.3.7.0

**Issue**
You can dupe Amber by crafting 4 Amber into a Amber Block, which can be crafted back into 9 Amber, duplicating it. Could be fixed by making Amber Blocks only be crafted from and into 4 Amber
![obrázek_2023-05-19_180036130](https://github.com/ThePansmith/Enigmatica2ExpertUnofficial/assets/93783103/b1c6be1a-78bc-465c-a39f-467b3f26a74e)
![obrázek_2023-05-19_180116526](https://github.com/ThePansmith/Enigmatica2ExpertUnofficial/assets/93783103/eb4e36ad-860d-42d1-af4f-e4b6a47a6e44)

**Comment by Anthonity** [comment]
this bug is also in the original e2e

**Comment by Spicierspace153** [comment]
issue resolved free to close
