### ISSUE TITLE
Suggestion: Add EnhancedP2P

### ISSUE THREAD

**Issue by Anthonity** [ThePansmith/Enigmatica2ExpertUnofficial#32]
**Modpack version**
E2Eu 1.3.8.1

**Suggestion**
EnhancedP2P is a fork of an AE2 addon Better P2P, which adds the Advaned Memory Card. It can be used to quickly search for P2P connections and name them. It's available at https://www.curseforge.com/minecraft/mc-mods/enhancedp2p and was featured on the June 2023 edition of Pansmith's 1.12.2 Modding News

**Comment by ThePansmith** [comment]
That pansmith fellow sure has some great ideas :trollface:. 

EnhancedP2P is planned for the next update, I will close this issue when it occurs.
