### ISSUE TITLE
Optifine Support

### ISSUE THREAD

**Issue by redznn** [ThePansmith/Enigmatica2ExpertUnofficial#36]
**Modpack version**
1.3.8.1

**Issue**
Not open with optifine, please fix

**Comment by ThePansmith** [comment]
no

**Comment by Xoggas** [comment]
Best support in the world 👍

**Comment by Xoggas** [comment]
> **Modpack version** 1.3.8.1
> 
> **Issue** Not open with optifine, please fix

Try downloading OptiFine HD U G6 pre1, it worked for me
