### ISSUE TITLE
Missing Nutrition mod

### ISSUE THREAD

**Issue by ZombieKM** [ThePansmith/Enigmatica2ExpertUnofficial#4]
**Modpack version**
1.0.4

**Issue**
Missing the 'Nutrition' mod by WesCook. It's in the original E2E.

**Logs**
N/A

**Comment by ThePansmith** [comment]
Held a vote about adding it back, community voted no.

Frankly the mod added nothing to the pack and removing it (even if on accident) could be seen as a form of QoL in itself :trollface:.
