### ISSUE TITLE
Suggestion: Replace Ice and Fire with Ice and Fire: RotN Edition

### ISSUE THREAD

**Issue by Palyon-dev** [ThePansmith/Enigmatica2ExpertUnofficial#45]
https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-rotn-edition

This fork of Ice and Fire has backported Lightning Dragons as well as a few other additions.

**Comment by Spicierspace153** [comment]
sadly not going to.
ice and fire  is here to be more like the original pack
thanks for the advice tho.
