### ISSUE TITLE
Fast hammers bugging

### ISSUE THREAD

**Issue by zentaos** [ThePansmith/Enigmatica2ExpertUnofficial#50]
**Modpack version**
1.3.9.2

**Issue**
https://discord.com/channels/914926812948234260/1082013266299064422/1217579021240631427

Hammer:
![image](https://github.com/ThePansmith/Enigmatica2ExpertUnofficial/assets/988308/29b50e21-9a97-46d0-9e5e-a27ce92bac7a)

**Logs**
Not needed

**Comment by Spicierspace153** [comment]
Thanks for posting
can i see what specs your running this doesn't actually look like a hammer error but a graphical error
do you have optifine installed?

**Comment by zentaos** [comment]
> Thanks for posting can i see what specs your running this doesn't actually look like a hammer error but a graphical error do you have optifine installed?

No, default pack.
You can try it by making a hammer with high speed

**Comment by Spicierspace153** [comment]
ok thank you 
ill look into it 
thanks for your help

**Comment by Spicierspace153** [comment]
could you send your specs?

**Comment by zentaos** [comment]
Client:
i7 4790, 32GB RAM, RX580 8GB

Server:
i7 6900, 64GB RAM, NVME SSD

**Comment by Spicierspace153** [comment]
this is a server issue due to your ping
nothing I can fix
