### ISSUE TITLE
Shift + Rightclick broken while flying due to Aqua Acrobatics

### ISSUE THREAD

**Issue by ThePixelbrain** [ThePansmith/Enigmatica2ExpertUnofficial#53]
**Modpack version**
1.3.9.2

**Issue**
The EnderIO Staff of Travelling can teleport you a short distance forward (also through blocks) when shift right clicking it. This works fine on the ground, but stops working at all when you have any creative flight enabled (tested with creative mode and Angel Ring).

Happens in both SP and MP. This bug does not appear in regular E2E.

**Steps to reproduce:**
1. Create a SP creative world
2. Get a Staff of Travelling from EnderIO
3. Fly
4. Shift Rightclick with the Staff of Travelling

**Logs**
N/A

**Comment by Spicierspace153** [comment]
Hey thank you for submitting the error,
is it still happening?

**Comment by Spicierspace153** [comment]
changed ender io version to fix error.
should work after latest patch update

**Comment by ThePixelbrain** [comment]
I'm confused by your message. What do you mean with "latest patch update"?

Do you mean your last PR #54? Because this PR doesn't change the EnderIO version.

**Comment by ThePixelbrain** [comment]
I did some further investigation and found out this issue is not limited to EnderIO, but instead happens with many mods. This lead me to believe that the shift rightclick handling is broken in general. Digging a bit deeper I took a good guess and figured out Aqua Acrobatics is the offending mod.

This issue is already reported in https://github.com/embeddedt/aquaacrobatics/issues/115 and fixed with Aqua Acrobatics 1.15.3 or above. E2EU uses 1.15.2. Newer versions have been out for quite some time, which leads me to believe that there was a reason to not update Aqua Acrobatics further?

**Comment by Spicierspace153** [comment]
no there is not a reason to update it..
i will update it when i have a moment

**Comment by Spicierspace153** [comment]
on the next modpack update this mod should be updated. so the issue should be resolved

**Comment by Spicierspace153** [comment]
hey this is resolved!
sorry about the long wait. 
check my latest commit
