### ISSUE TITLE
Wierd visual issue with things

### ISSUE THREAD

**Issue by zcarp7220** [ThePansmith/Enigmatica2ExpertUnofficial#55]
**Modpack version**
1.3.9.2

**Issue**
All entities stay within the relitive view of the player if the player was looking straight forward. Also there is a random blue thing that renders in the player
![2024-04-27_22 25 59](https://github.com/ThePansmith/Enigmatica2ExpertUnofficial/assets/64746099/089ce18f-5772-4aeb-9f1d-242c79f4a3cd)
![2024-04-27_22 27 12](https://github.com/ThePansmith/Enigmatica2ExpertUnofficial/assets/64746099/d3cfe0f9-de0f-4289-a259-dd30c1f82f42)
![2024-04-27_22 27 30](https://github.com/ThePansmith/Enigmatica2ExpertUnofficial/assets/64746099/7e8d3284-afac-4c47-82ef-ac9d347abb42)

![2024-04-27_22 25 55](https://github.com/ThePansmith/Enigmatica2ExpertUnofficial/assets/64746099/5018aaf0-68c8-4293-81bb-4b92a5e38406)
thin your file

 

**Logs**
Lost the log file

**Comment by Spicierspace153** [comment]
can i see your video settings?
is this issue still a thing

**Comment by Spicierspace153** [comment]
closing issue
