### ISSUE TITLE
Tin electron tube doesn't have a recipe in multiblock

### ISSUE THREAD

**Issue by Qualc1** [ThePansmith/Enigmatica2ExpertUnofficial#6]
**Modpack version**
1.0.4
**Issue**
The Forestry's tin electron tube doesn't have a recipe in Advanced Thermionic Fabricator multiblock.
Instead, 5 tin ad 2 redstone will craft the iron electron tubes.
![2023-03-23_08 43 27](https://user-images.githubusercontent.com/67223932/227138351-8494d75e-87a1-4ab1-9362-406e3a796325.png)
![2023-03-23_08 42 56](https://user-images.githubusercontent.com/67223932/227138057-f7ae099e-4997-401f-9ac1-b31e6dd7e8ef.png)

**Comment by ThePansmith** [comment]
Fixed in 1.0.4
