### ISSUE TITLE
Dilithium Name Fix

### ISSUE THREAD

**Issue by Osmith0** [ThePansmith/Enigmatica2ExpertUnofficial#7]
Modpack version:
1.0.5

Issue:
The name of the Dilithium crystal/dust/ore names aru bugged (ex: dilithium crystal name is "material.Dilithium.name Crystal"). 
To fix this i would suggest to add this string "material.Dilithium.name=Dilithium" in the lang file located in "Enigmatica 2 Expert Unofficial - E2Eu\scripts\contenttweaker" this will fix the name for all the items. (crystal/dust/ore)

**Comment by ThePansmith** [comment]
Thanks for submitting! Fixed in 99e152c.
